### PR TITLE
Pull Up Constructor: Should check for constructor

### PR DESCRIPTION
**Pull request by ramtin-ehsani**
### **Group 5, Pull up constructor, Fix issue 70**
-  Implementing extract method refactoring `Arman Heydari, Amin Ghasvari`
- Implementing pull up constructor refactoring `Ramtin Ehsani`
- Fix issues & testing pull up method refactoring `Amir Hossein Ghasemi`

Fixed the issue of pull-up constructor refactoring mentioned in #70.

#48, #70

### CODE REVIEW

**Review by seyyedaliayati — CHANGES_REQUESTED** [review]
Consider my use-case: I have a class called Manager that extends from Employee as follow
```
public class Manager extends Employee {
    public Manager(String name, String id, int grade) {
        this.name = name;
        this.id = id;
        this.grade = grade;
    }
}
```
And here is my employee class:
```
public class Employee {
    String name;
    String id;
    int grade;

    public Employee(String name, String id, int grade) {
        System.out.println("Two argument constructor");
        this.name = name;
        this.id = id;
        this.grade = grade;
    }


    public Employee(){
        System.out.println("Zero argument constructor");
    }
}
```
as it is obvious I want to reduce my duplicated code in the constructor by pulling it up can calling the super class related constructor! I executed your code but I got two major errors:
1. The super call must be the first statement in constructor!
Screenshot from 2021-06-30 10-05-22
2. What is this ? ://
Screenshot from 2021-06-30 10-07-29

**Comment by ramtin-ehsani** [comment]
> Consider my use-case: I have a class called Manager that extends from Employee as follow
> 
> ```
> public class Manager extends Employee {
>     public Manager(String name, String id, int grade) {
>         this.name = name;
>         this.id = id;
>         this.grade = grade;
>     }
> }
> ```
> 
> And here is my employee class:
> 
> ```
> public class Employee {
>     String name;
>     String id;
>     int grade;
> 
>     public Employee(String name, String id, int grade) {
>         System.out.println("Two argument constructor");
>         this.name = name;
>         this.id = id;
>         this.grade = grade;
>     }
> 
> 
>     public Employee(){
>         System.out.println("Zero argument constructor");
>     }
> }
> ```
> 
> as it is obvious I want to reduce my duplicated code in the constructor by pulling it up can calling the super class related constructor! I executed your code but I got two major errors:
> 
> 1. The super call must be the first statement in constructor!
>    Screenshot from 2021-06-30 10-05-22
> 2. What is this ? ://
>    Screenshot from 2021-06-30 10-07-29

@seyyedaliayati 
I think that you're using the refactor in a wrong way. because I tested the same use-case and it was ok!
The use-case I tested can be viewed in the following video:

https://user-images.githubusercontent.com/51258896/123921486-49ba3e00-d99c-11eb-9442-aecddd94bfbf.mp4

**Review by seyyedaliayati — CHANGES_REQUESTED** [review]
I checked again.
You are right. If my classes have a package it works but my classes are in the root of the project ( in src/) and they don't belong to any package. Try your use-case in the video without package name!
After that there is another problem. This code rewrites the super class constructor. For example look at the following screen shot. I have a line for printing but it removed after refactoring. Suppose that this line was very important and your not allowed to delete or modify it.
Screenshot from 2021-06-30 13-10-37

**Comment by ramtin-ehsani** [comment]
> I checked again.
> You are right. If my classes have a package it works but my classes are in the root of the project ( in src/) and they don't belong to any package. Try your use-case in the video without package name!
> After that there is another problem. This code rewrites the super class constructor. For example look at the following screen shot. I have a line for printing but it removed after refactoring. Suppose that this line was very important and your not allowed to delete or modify it.
> Screenshot from 2021-06-30 13-10-37

When the child is inheriting the super class, it doesn't want the print code to be called in its class (I think so) when calling the super method. So what should be done? I guess it's not related to pull up constructor refactoring.

**Comment by seyyedaliayati** [comment]
> > I checked again.
> > You are right. If my classes have a package it works but my classes are in the root of the project ( in src/) and they don't belong to any package. Try your use-case in the video without package name!
> > After that there is another problem. This code rewrites the super class constructor. For example look at the following screen shot. I have a line for printing but it removed after refactoring. Suppose that this line was very important and your not allowed to delete or modify it.
> > Screenshot from 2021-06-30 13-10-37
> 
> @seyyedaliayati
> When the child is inheriting the super class, it doesn't want the print code to be called in its class (I think so) when calling the super method. So what should be done? I guess it's not related to pull up constructor refactoring.

Actually it is related. deleting some lines form code after refactoring  makes it unreliable because we don't know what's written.
So:
1. Try to don't delete extra lines.
2. Fix your code to work with no-package classes! (I mean package_name="" or None)

**Comment by ramtin-ehsani** [comment]
> > > I checked again.
> > > You are right. If my classes have a package it works but my classes are in the root of the project ( in src/) and they don't belong to any package. Try your use-case in the video without package name!
> > > After that there is another problem. This code rewrites the super class constructor. For example look at the following screen shot. I have a line for printing but it removed after refactoring. Suppose that this line was very important and your not allowed to delete or modify it.
> > > Screenshot from 2021-06-30 13-10-37
> > 
> > 
> > @seyyedaliayati
> > When the child is inheriting the super class, it doesn't want the print code to be called in its class (I think so) when calling the super method. So what should be done? I guess it's not related to pull up constructor refactoring.
> 
> Actually it is related. deleting some lines form code after refactoring makes it unreliable because we don't know what's written.
> So:
> 
> 1. Try to don't delete extra lines.
> 2. Fix your code to work with no-package classes! (I mean package_name="" or None)

@seyyedaliayati
Ok. Please merge this pull request as it fixes the issue mentioned in the description. If we have any time left in the following weeks, we will try to fix the things you mentioned as well.

**Comment by ramtin-ehsani** [comment]
@seyyedaliayati 
I fixed the issue of deleting extra lines and added a pre condition that package name should be specified. Please read my last comment in here as well and close the issues that are open. thanks!

**Comment by seyyedaliayati** [comment]
> @seyyedaliayati
> I fixed the issue of deleting extra lines and added a pre condition that package name should be specified. Please read my last comment in here as well and close the issues that are open. thanks!

Specifying and forcing to provide a package is not a pre-condition and your code should without package too! Sorry but I can't merge this pull request! Try to fix ASAP.

**Review by seyyedaliayati — CHANGES_REQUESTED** [review]
Code should work with classes that does not to any package too!

**Comment by ramtin-ehsani** [comment]
Dear @seyyedaliayati ,
I fixed the issue of empty package name and now empty packages are supported using "".
Please merge this pull-request and close the related open issues. Thanks!

**Comment by seyyedaliayati** [comment]
Merged in https://github.com/m-zakeri/CodART/commit/f18a234e53cc3fcb6c615a47a77e274ad72f8a39

**Pull request closed without merging**
