### PR TITLE
Encapsulate field

### PR DESCRIPTION
**Pull request by mossj77**
### **New changes:** 

- Use new grammar (JavaParserLabeled grammar) 
- Write/Change listener codes based on new grammar
- Solve the issue of the duplicate setter/getter
- Make private fields that don't have any modifier (and add  setter/getter to code if necessary)

### CODE REVIEW

**Review by seyyedaliayati — CHANGES_REQUESTED** [review]
1. First of all please use PEP8 for code styling for example variable in function should be **lowercase** 
2. Use relative path and OS module for path. For example `test_file = FileStream(str(Path + "src/my_package/Source.java"))` is not recommended!
3. I think this refactoring should get a project directory, class name, field name as input but you run your code on a single file.
4. You should rewrite refactored code on same existing files
5. I executed following code but I got this error:
**Executed:**
```
def main():
    Path = "/data/Dev/JavaSample/"
    test_file = FileStream(str(Path + "src/my_package/Source.java"))
    print("file opened")
    Refactored = open(os.path.join(Path, "use_field_propagation_test_refactored.java"), 'w', newline='')

    Lexer = JavaLexer(test_file)

    TokenStream = CommonTokenStream(Lexer)

    Parser = JavaParserLabeled(TokenStream)

    EFlistener = EncapsulateFiledRefactoringListener(TokenStream, 'number3')
    Tree = Parser.compilationUnit()

    Walker = ParseTreeWalker()
    Walker.walk(t=Tree, listener=EFlistener)

    Refactored.write(EFlistener.token_stream_rewriter.getDefaultText())
    print("finished!!!!!!!!")


if __name__ == "__main__":
    main()
```
**Result:**
```
file opened
Traceback (most recent call last):
  File "/data/Dev/CodART/refactorings/encapsulate_field.py", line 171, in <module>
    main()
  File "/data/Dev/CodART/refactorings/encapsulate_field.py", line 164, in main
    Walker.walk(t=Tree, listener=EFlistener)
  File "/data/Dev/CodART/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 157, in walk
    self.enterRule(listener, t)
  File "/data/Dev/CodART/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 177, in enterRule
    ctx.enterRule(listener)
  File "/data/Dev/CodART/gen/javaLabeled/JavaParserLabeled.py", line 1093, in enterRule
    listener.enterCompilationUnit(self)
  File "/data/Dev/CodART/refactorings/encapsulate_field.py", line 143, in enterCompilationUnit
    self.token_stream_rewriter.replaceRange(from_idx=hidden[0].tokenIndex,
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

```

**Comment by SadraGoudarzdashti** [comment]
please check our last commit.

**Review by seyyedaliayati — CHANGES_REQUESTED** [review]
Salam, I reviewed your code, almost everything is OK except there are minor issues that are easy to fix, so please fix those and commit again:
1. I think it is better include package name as input too. (None or empty for no-package classes)
For example it's better convert this part of code:
```python
if __name__ == "__main__":
    directory_path = "/data/Dev/JavaSample/src/my_package/"
    source_class = 'Source'
    field_name = 'number3'
    main(directory_path, source_class, field_name)
```
to this:
```python
if __name__ == "__main__":
    directory_path = "/data/Dev/JavaSample/"
    package_name = "my_package"
    source_class = 'Source'
    field_name = 'number3'
    main(directory_path, package_name, source_class, field_name)
```
2. Propagation is not working. I used the field in another class but it gives me this error after running the JavaSample project.
```java
App Started...
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
        The field Source.number3 is not visible

        at User.<init>(User.java:12)
        at App.main(App.java:4)
```

**Comment by seyyedaliayati** [comment]
سلام اومدید ابرو درست کنید زدید چشمش رو کور کردید
همونقدری هم که کار میکرد دیگه کار نمیکنه :)

**Pull request merged**
